version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vietfi-address-code"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12bim3a7zr6k3"
s3_prefix = "vietfi-address-code"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

<<<<<<< Updated upstream
resolve_s3 = true
confirm_changeset = true

=======
parameter_overrides = "BucketName=\"vietfi-api-data\" DataFileKey=\"country_div_sub.sqlite3\" CorsAllowOrigin=\"'https://vietfi-api-data.s3.ap-southeast-1.amazonaws.com'\""
resolve_s3 = true
>>>>>>> Stashed changes
