AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vietfi-address-code

  SAM Template for AddressCodeFunction

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Parameters:
  BucketName:
    Type: String
    Description: Bucket name for get DB File
  DataFileKey:
    Type: String
    Default: "country_div_sub.sqlite3"

Resources:
  AddressCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: address_code_func/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          TZ: Asia/Ho_Chi_Minh
          BUCKET_NAME: !Ref BucketName
          DB_FILE_KEY: !Ref DataFileKey
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucket
              - s3:PutObject
            Resource: 
              - !Sub 'arn:aws:s3:::${BucketName}/*'
              - !Sub 'arn:aws:s3:::${BucketName}'

      Architectures:
        - x86_64
      Events:
        CountryList:
          Type: Api
          Properties:
            Path: /countries
            Method: get
        CountryGet:
          Type: Api
          Properties:
            Path: /countries/{iso_code}
            Method: get

Outputs:
  AddressCodeApi:
    Description: "API Gateway endpoint URL for Prod stage for AddressCodeFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/countries/"
  AddressCodeFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AddressCodeFunction.Arn
  AddressCodeFunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt AddressCodeFunction.Arn
