AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vietfi-address-code

  SAM Template for AddressFunction

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  AddressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: address_code_func/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CountryList:
          Type: Api
          Properties:
            Path: /countries
            Method: get
        CountryGet:
          Type: Api
          Properties:
            Path: /countries/{iso_code}
            Method: get
        DivisionList:
          Type: Api
          Properties:
            RestApiId: !Ref AddressCodeApi
            Path: /countries/{iso_code}/divisions
            Method: get


Outputs:
  AddressApi:
    Description: "API Gateway endpoint URL for Prod stage for AddressCodeFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/countries/"
  AddressFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AddressFunction.Arn
  AddressFunctionIamRole:
    Description: "Implicit IAM Role created for the function"
    Value: !GetAtt AddressFunction.Arn